# - Find TinyXML
# Find the TinyXML include directory and library
#
#   TINYXML_FOUND       - True if TinyXML found.
#   TINYXML_INCLUDE_DIR - Where to find tinyxml.h
#   TINYXML_LIBRARIES   - List of libraries for linking.
#

FIND_PATH(TINYXML_INCLUDE_DIR tinyxml.h)
FIND_LIBRARY(TINYXML_LIBRARIES tinyxml)

IF(TINYXML_INCLUDE_DIR AND TINYXML_LIBRARIES)
	MESSAGE(STATUS "TinyXML library found: ${TINYXML_LIBRARIES}")
	SET(TINYXML_FOUND 1)
ELSE(TINYXML_INCLUDE_DIR AND TINYXML_LIBRARIES)
	MESSAGE(STATUS "Unable to find TinyXML")
ENDIF(TINYXML_INCLUDE_DIR AND TINYXML_LIBRARIES)
